services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: movies
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 10

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:devpass@db:5432/movies
      DB_DRIVER: node-postgres
      TMDB_ACCESS_TOKEN: ${TMDB_ACCESS_TOKEN}
      AUTH_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
